### ISSUE TITLE
Problematic macpaint file

### ISSUE THREAD

**Issue by Sembiance** [jsummers/deark#61] opened 2023-10-15 16:22 UTC
The attached [abydos.mac.zip](https://github.com/jsummers/deark/files/12910061/abydos.mac.zip) macPaint file when converted with deark built from code dated `2023-09-26` shows up as:
![output 000](https://github.com/jsummers/deark/assets/81436/b6f37fb0-ca16-466b-9ca2-f1d58f8b5d46)

However other programs such as ImageMagick, recoil and others show it correctly as: ![imageMagick](https://github.com/jsummers/deark/assets/81436/b1993719-cb8c-4506-81a9-abab579766b0)

Is this a deark bug?

**Comment by jsummers** [comment] 2023-10-16 20:32
Thanks for reporting this.

The file seems to be malformed, but I think I can pretty easily make Deark support it, without much risk of breaking anything.

You could also use the option "-opt macpaint:macbinary=0", but that will break most other MacPaint files.

(The issue is that, in real MacPaint files, an RLE run will never cross a row boundary. But in this file, that happens, and it causes Deark to mis-detect the format.)

**Comment by jsummers** [comment] 2023-10-18 12:31
Should be fixed now.

**Closed** 2023-10-18 12:31 UTC
